name: Quinn Pollock

description: Quinn Pollock's Site where I talk about my thoughts

url: "https://quinnpollock.net"

title: Quinn Pollock's Site 

permalink: /:categories/:title/

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

baseurl:

include:
  - _redirects
  - netlify.toml